import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

const solidDir = path.resolve('src/assets/icons/solid')
const outlinedDir = path.resolve('src/assets/icons/outlined')
const scssPath = path.resolve('src/styles/components/_icons.scss')
const iconsDataPath = path.resolve('src/plugins/icons.js')

// Read all .svg files from solid and outlined directories
const solidFiles = fs.existsSync(solidDir)
  ? fs.readdirSync(solidDir).filter(f => f.endsWith('.svg')).map(f => path.basename(f, '.svg'))
  : []

const outlinedFiles = fs.existsSync(outlinedDir)
  ? fs.readdirSync(outlinedDir).filter(f => f.endsWith('.svg')).map(f => path.basename(f, '.svg'))
  : []

// Unique sorted icon names
const iconNames = Array.from(new Set([...solidFiles, ...outlinedFiles])).sort()

// Ensure both solid and outlined variants exist (fallback to each other if one is missing)
for (const name of iconNames) {
  const solidTarget = path.join(solidDir, `${name}.svg`)
  const outlinedTarget = path.join(outlinedDir, `${name}.svg`)

  if (!fs.existsSync(outlinedTarget) && fs.existsSync(solidTarget)) {
    fs.copyFileSync(solidTarget, outlinedTarget)
  } else if (!fs.existsSync(solidTarget) && fs.existsSync(outlinedTarget)) {
    fs.copyFileSync(outlinedTarget, solidTarget)
  }
}

// 1. Update $jui-icons in _icons.scss
let scssContent = fs.readFileSync(scssPath, 'utf-8')
const formattedList = `$jui-icons: (\n  ${iconNames.map(n => `'${n}'`).join(',\n  ')}\n);`

scssContent = scssContent.replace(/\$jui-icons:\s*\([\s\S]*?\);/, formattedList)
fs.writeFileSync(scssPath, scssContent, 'utf-8')

// 2. Helper to infer category & default tags for new icons
function inferCategoryAndTags(name) {
  const tags = name.split('-').filter(Boolean)

  if (name.startsWith('arrow-') || name.startsWith('chevron-') || name.startsWith('circle-chevron-')) {
    return { category: 'Arrows', tags: [...tags, 'direction', 'pointer'] }
  }
  if (['truck', 'cart', 'credit-card', 'chart', 'tag', 'wallet', 'dollar', 'receipt'].includes(name)) {
    return { category: 'Commerce', tags: [...tags, 'business', 'commerce'] }
  }
  if (['home', 'search', 'bell', 'gear', 'envelope', 'envelope-open', 'user', 'users', 'globe', 'compass', 'location', 'map'].includes(name)) {
    return { category: 'Navigation', tags: [...tags, 'nav', 'general'] }
  }
  if (['lock', 'unlock', 'eye', 'eye-slash', 'sun', 'moon', 'copyright', 'shield', 'key'].includes(name)) {
    return { category: 'System', tags: [...tags, 'security', 'system'] }
  }
  if (['circle-info', 'circle-check', 'circle-xmark', 'triangle-exclamation'].includes(name)) {
    return { category: 'Status', tags: [...tags, 'status', 'feedback'] }
  }
  if (['heart', 'star', 'image', 'file', 'folder', 'calendar', 'clock', 'a', 'b', 'c'].includes(name)) {
    return { category: 'Media', tags: [...tags, 'media', 'content'] }
  }
  return { category: 'Action', tags: [...tags, 'action', 'control'] }
}

// 3. Load existing icon metadata from src/data/icons.js if present
const existingIconsMap = new Map()
if (fs.existsSync(iconsDataPath)) {
  try {
    const fileUrl = pathToFileURL(iconsDataPath).href
    const imported = await import(`${fileUrl}?update=${Date.now()}`)
    if (Array.isArray(imported.allIcons)) {
      for (const item of imported.allIcons) {
        if (item && item.name) {
          existingIconsMap.set(item.name, item)
        }
      }
    }
  } catch (err) {
    console.warn('Could not read existing src/data/icons.js, generating fresh catalog.', err.message)
  }
}

// Build merged list preserving custom categories and tags
const mergedIcons = iconNames.map(name => {
  if (existingIconsMap.has(name)) {
    return existingIconsMap.get(name)
  }
  const inferred = inferCategoryAndTags(name)
  return {
    name,
    category: inferred.category,
    tags: inferred.tags,
  }
})

// Categories list
const categories = ['All', 'Navigation', 'Action', 'Arrows', 'Commerce', 'Media', 'System', 'Status']

// Ensure src/data directory exists
const dataDir = path.dirname(iconsDataPath)
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true })
}

// Write src/plugins/icons.js
const iconsJsContent = `// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/sync-icons.mjs
// Run "npm run icons:sync" to update this catalog.
// ============================================================================

export const categories = ${JSON.stringify(categories, null, 2)}

export const allIcons = ${JSON.stringify(mergedIcons, null, 2)}

export default allIcons
`

fs.writeFileSync(iconsDataPath, iconsJsContent, 'utf-8')

console.log(`✓ Successfully synced ${iconNames.length} icons into _icons.scss and src/plugins/icons.js!`)
