// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/sync-icons.mjs
// Run "npm run icons:sync" to update this catalog.
// ============================================================================

export const categories = [
  "All",
  "Navigation",
  "Action",
  "Arrows",
  "Commerce",
  "Media",
  "System",
  "Status"
]

export const allIcons = [
  {
    "name": "a",
    "category": "Media",
    "tags": [
      "letter",
      "alphabet",
      "font",
      "typography",
      "text"
    ]
  },
  {
    "name": "arrow-back",
    "category": "Arrows",
    "tags": [
      "arrow",
      "back",
      "direction",
      "pointer"
    ]
  },
  {
    "name": "arrow-back-up",
    "category": "Arrows",
    "tags": [
      "arrow",
      "back",
      "up",
      "direction",
      "pointer"
    ]
  },
  {
    "name": "arrow-back-up-double",
    "category": "Arrows",
    "tags": [
      "arrow",
      "back",
      "up",
      "double",
      "direction",
      "pointer"
    ]
  },
  {
    "name": "arrow-down",
    "category": "Arrows",
    "tags": [
      "bottom",
      "descend",
      "direction",
      "south"
    ]
  },
  {
    "name": "arrow-left",
    "category": "Arrows",
    "tags": [
      "back",
      "previous",
      "direction",
      "west"
    ]
  },
  {
    "name": "arrow-right",
    "category": "Arrows",
    "tags": [
      "forward",
      "next",
      "direction",
      "east"
    ]
  },
  {
    "name": "arrow-up",
    "category": "Arrows",
    "tags": [
      "top",
      "ascend",
      "direction",
      "north"
    ]
  },
  {
    "name": "b",
    "category": "Media",
    "tags": [
      "letter",
      "alphabet",
      "font",
      "typography",
      "text"
    ]
  },
  {
    "name": "bars",
    "category": "Action",
    "tags": [
      "bars",
      "action",
      "control"
    ]
  },
  {
    "name": "bell",
    "category": "Navigation",
    "tags": [
      "alert",
      "notification",
      "alarm",
      "ring"
    ]
  },
  {
    "name": "c",
    "category": "Media",
    "tags": [
      "letter",
      "alphabet",
      "font",
      "typography",
      "text"
    ]
  },
  {
    "name": "calendar",
    "category": "Media",
    "tags": [
      "date",
      "schedule",
      "event",
      "month"
    ]
  },
  {
    "name": "camera-plus",
    "category": "Action",
    "tags": [
      "camera",
      "plus",
      "action",
      "control"
    ]
  },
  {
    "name": "cart",
    "category": "Commerce",
    "tags": [
      "shopping",
      "store",
      "basket",
      "buy",
      "checkout"
    ]
  },
  {
    "name": "chart",
    "category": "Commerce",
    "tags": [
      "analytics",
      "metrics",
      "graph",
      "data",
      "sales"
    ]
  },
  {
    "name": "check",
    "category": "Action",
    "tags": [
      "tick",
      "confirm",
      "success",
      "done",
      "ok"
    ]
  },
  {
    "name": "chevron-down",
    "category": "Arrows",
    "tags": [
      "down",
      "angle",
      "caret",
      "accordion"
    ]
  },
  {
    "name": "chevron-left",
    "category": "Arrows",
    "tags": [
      "previous",
      "angle",
      "caret"
    ]
  },
  {
    "name": "chevron-right",
    "category": "Arrows",
    "tags": [
      "next",
      "angle",
      "caret"
    ]
  },
  {
    "name": "chevron-up",
    "category": "Arrows",
    "tags": [
      "up",
      "angle",
      "caret",
      "accordion"
    ]
  },
  {
    "name": "circle-check",
    "category": "Status",
    "tags": [
      "success",
      "valid",
      "approved",
      "pass"
    ]
  },
  {
    "name": "circle-chevron-down",
    "category": "Arrows",
    "tags": [
      "down",
      "expand",
      "circle",
      "angle",
      "caret"
    ]
  },
  {
    "name": "circle-chevron-left",
    "category": "Arrows",
    "tags": [
      "back",
      "previous",
      "circle",
      "angle",
      "caret"
    ]
  },
  {
    "name": "circle-chevron-right",
    "category": "Arrows",
    "tags": [
      "next",
      "forward",
      "circle",
      "angle",
      "caret"
    ]
  },
  {
    "name": "circle-chevron-up",
    "category": "Arrows",
    "tags": [
      "up",
      "collapse",
      "circle",
      "angle",
      "caret"
    ]
  },
  {
    "name": "circle-info",
    "category": "Status",
    "tags": [
      "information",
      "help",
      "details",
      "notice"
    ]
  },
  {
    "name": "circle-xmark",
    "category": "Status",
    "tags": [
      "error",
      "failed",
      "invalid",
      "rejected"
    ]
  },
  {
    "name": "clock",
    "category": "Media",
    "tags": [
      "time",
      "history",
      "watch",
      "duration"
    ]
  },
  {
    "name": "coins",
    "category": "Action",
    "tags": [
      "coins",
      "action",
      "control"
    ]
  },
  {
    "name": "copy",
    "category": "Action",
    "tags": [
      "duplicate",
      "clipboard",
      "clone"
    ]
  },
  {
    "name": "copyright",
    "category": "System",
    "tags": [
      "license",
      "legal",
      "rights",
      "author",
      "c"
    ]
  },
  {
    "name": "credit-card",
    "category": "Commerce",
    "tags": [
      "payment",
      "billing",
      "finance",
      "visa",
      "card"
    ]
  },
  {
    "name": "d",
    "category": "Action",
    "tags": [
      "d",
      "action",
      "control"
    ]
  },
  {
    "name": "download",
    "category": "Action",
    "tags": [
      "save",
      "get",
      "export",
      "disk"
    ]
  },
  {
    "name": "e",
    "category": "Action",
    "tags": [
      "e",
      "action",
      "control"
    ]
  },
  {
    "name": "edit",
    "category": "Action",
    "tags": [
      "edit",
      "action",
      "control"
    ]
  },
  {
    "name": "envelope",
    "category": "Navigation",
    "tags": [
      "mail",
      "message",
      "email",
      "inbox"
    ]
  },
  {
    "name": "envelope-open",
    "category": "Navigation",
    "tags": [
      "mail",
      "message",
      "email",
      "read",
      "letter"
    ]
  },
  {
    "name": "eye",
    "category": "System",
    "tags": [
      "visible",
      "view",
      "show",
      "preview"
    ]
  },
  {
    "name": "eye-slash",
    "category": "System",
    "tags": [
      "hidden",
      "hide",
      "invisible",
      "mask"
    ]
  },
  {
    "name": "f",
    "category": "Action",
    "tags": [
      "f",
      "action",
      "control"
    ]
  },
  {
    "name": "file",
    "category": "Media",
    "tags": [
      "document",
      "page",
      "text",
      "attachment"
    ]
  },
  {
    "name": "filter",
    "category": "Action",
    "tags": [
      "funnel",
      "sort",
      "refine"
    ]
  },
  {
    "name": "floppy-disk",
    "category": "Action",
    "tags": [
      "floppy",
      "disk",
      "action",
      "control"
    ]
  },
  {
    "name": "folder",
    "category": "Media",
    "tags": [
      "directory",
      "files",
      "storage",
      "project"
    ]
  },
  {
    "name": "g",
    "category": "Action",
    "tags": [
      "g",
      "action",
      "control"
    ]
  },
  {
    "name": "gear",
    "category": "Navigation",
    "tags": [
      "settings",
      "cog",
      "preferences",
      "options"
    ]
  },
  {
    "name": "globe",
    "category": "Navigation",
    "tags": [
      "world",
      "earth",
      "internet",
      "web"
    ]
  },
  {
    "name": "h",
    "category": "Action",
    "tags": [
      "h",
      "action",
      "control"
    ]
  },
  {
    "name": "heart",
    "category": "Media",
    "tags": [
      "like",
      "favorite",
      "love",
      "wishlist"
    ]
  },
  {
    "name": "home",
    "category": "Navigation",
    "tags": [
      "house",
      "main",
      "dashboard",
      "root"
    ]
  },
  {
    "name": "i",
    "category": "Action",
    "tags": [
      "i",
      "action",
      "control"
    ]
  },
  {
    "name": "image",
    "category": "Media",
    "tags": [
      "photo",
      "picture",
      "gallery",
      "graphic"
    ]
  },
  {
    "name": "j",
    "category": "Action",
    "tags": [
      "j",
      "action",
      "control"
    ]
  },
  {
    "name": "k",
    "category": "Action",
    "tags": [
      "k",
      "action",
      "control"
    ]
  },
  {
    "name": "lock",
    "category": "System",
    "tags": [
      "secure",
      "password",
      "protected",
      "auth"
    ]
  },
  {
    "name": "m",
    "category": "Action",
    "tags": [
      "m",
      "action",
      "control"
    ]
  },
  {
    "name": "message",
    "category": "Action",
    "tags": [
      "message",
      "action",
      "control"
    ]
  },
  {
    "name": "minus",
    "category": "Action",
    "tags": [
      "remove",
      "subtract",
      "decrease",
      "collapse"
    ]
  },
  {
    "name": "moon",
    "category": "System",
    "tags": [
      "dark",
      "night",
      "theme",
      "mode"
    ]
  },
  {
    "name": "n",
    "category": "Action",
    "tags": [
      "n",
      "action",
      "control"
    ]
  },
  {
    "name": "newspaper",
    "category": "Action",
    "tags": [
      "newspaper",
      "action",
      "control"
    ]
  },
  {
    "name": "o",
    "category": "Action",
    "tags": [
      "o",
      "action",
      "control"
    ]
  },
  {
    "name": "p",
    "category": "Action",
    "tags": [
      "p",
      "action",
      "control"
    ]
  },
  {
    "name": "pen",
    "category": "Action",
    "tags": [
      "edit",
      "write",
      "pencil",
      "modify"
    ]
  },
  {
    "name": "piggybank",
    "category": "Action",
    "tags": [
      "piggybank",
      "action",
      "control"
    ]
  },
  {
    "name": "plus",
    "category": "Action",
    "tags": [
      "add",
      "create",
      "new",
      "insert"
    ]
  },
  {
    "name": "q",
    "category": "Action",
    "tags": [
      "q",
      "action",
      "control"
    ]
  },
  {
    "name": "r",
    "category": "Action",
    "tags": [
      "r",
      "action",
      "control"
    ]
  },
  {
    "name": "receipt",
    "category": "Commerce",
    "tags": [
      "receipt",
      "business",
      "commerce"
    ]
  },
  {
    "name": "recycle",
    "category": "Action",
    "tags": [
      "eco",
      "environment",
      "reuse",
      "green",
      "waste",
      "cycle"
    ]
  },
  {
    "name": "s",
    "category": "Action",
    "tags": [
      "s",
      "action",
      "control"
    ]
  },
  {
    "name": "search",
    "category": "Navigation",
    "tags": [
      "find",
      "magnifier",
      "lookup",
      "explore"
    ]
  },
  {
    "name": "share",
    "category": "Action",
    "tags": [
      "social",
      "forward",
      "send"
    ]
  },
  {
    "name": "spinner",
    "category": "Action",
    "tags": [
      "loading",
      "progress",
      "wait",
      "busy"
    ]
  },
  {
    "name": "star",
    "category": "Media",
    "tags": [
      "rating",
      "favorite",
      "bookmark",
      "score"
    ]
  },
  {
    "name": "sun",
    "category": "System",
    "tags": [
      "light",
      "brightness",
      "day",
      "mode"
    ]
  },
  {
    "name": "t",
    "category": "Action",
    "tags": [
      "t",
      "action",
      "control"
    ]
  },
  {
    "name": "trash",
    "category": "Action",
    "tags": [
      "delete",
      "remove",
      "bin",
      "garbage"
    ]
  },
  {
    "name": "trash-can",
    "category": "Action",
    "tags": [
      "delete",
      "remove",
      "bin",
      "garbage",
      "rubbish",
      "waste"
    ]
  },
  {
    "name": "triangle-exclamation",
    "category": "Status",
    "tags": [
      "warning",
      "caution",
      "alert",
      "notice"
    ]
  },
  {
    "name": "truck",
    "category": "Commerce",
    "tags": [
      "delivery",
      "shipping",
      "transport",
      "vehicle",
      "order"
    ]
  },
  {
    "name": "u",
    "category": "Action",
    "tags": [
      "u",
      "action",
      "control"
    ]
  },
  {
    "name": "unlock",
    "category": "System",
    "tags": [
      "open",
      "insecure",
      "accessible"
    ]
  },
  {
    "name": "upload",
    "category": "Action",
    "tags": [
      "send",
      "cloud",
      "import"
    ]
  },
  {
    "name": "user",
    "category": "Navigation",
    "tags": [
      "profile",
      "account",
      "person",
      "avatar"
    ]
  },
  {
    "name": "users",
    "category": "Navigation",
    "tags": [
      "team",
      "group",
      "people",
      "members"
    ]
  },
  {
    "name": "v",
    "category": "Action",
    "tags": [
      "v",
      "action",
      "control"
    ]
  },
  {
    "name": "w",
    "category": "Action",
    "tags": [
      "w",
      "action",
      "control"
    ]
  },
  {
    "name": "x",
    "category": "Action",
    "tags": [
      "x",
      "action",
      "control"
    ]
  },
  {
    "name": "xmark",
    "category": "Action",
    "tags": [
      "close",
      "cross",
      "cancel",
      "delete",
      "remove"
    ]
  },
  {
    "name": "y",
    "category": "Action",
    "tags": [
      "y",
      "action",
      "control"
    ]
  },
  {
    "name": "z",
    "category": "Action",
    "tags": [
      "z",
      "action",
      "control"
    ]
  }
]

export default allIcons
