/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/@core/components/AppLogo.vue')['default']
    JAlert: typeof import('./src/@core/components/JAlert.vue')['default']
    JBtn: typeof import('./src/@core/components/JBtn.vue')['default']
    JCard: typeof import('./src/@core/components/JCard.vue')['default']
    JCheckbox: typeof import('./src/@core/components/JCheckbox.vue')['default']
    JDataTable: typeof import('./src/@core/components/JDataTable.vue')['default']
    JDatePicker: typeof import('./src/@core/components/JDatePicker.vue')['default']
    JIcon: typeof import('./src/@core/components/JIcon.vue')['default']
    JInput: typeof import('./src/@core/components/JInput.vue')['default']
    JModal: typeof import('./src/@core/components/JModal.vue')['default']
    JPagination: typeof import('./src/@core/components/JPagination.vue')['default']
    JRadio: typeof import('./src/@core/components/JRadio.vue')['default']
    JSelect: typeof import('./src/@core/components/JSelect.vue')['default']
    JSwitch: typeof import('./src/@core/components/JSwitch.vue')['default']
    JTabs: typeof import('./src/@core/components/JTabs.vue')['default']
    JTextarea: typeof import('./src/@core/components/JTextarea.vue')['default']
    JTimePicker: typeof import('./src/@core/components/JTimePicker.vue')['default']
    JToast: typeof import('./src/@core/components/JToast.vue')['default']
    JToastContainer: typeof import('./src/@core/components/JToastContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AppLogo: typeof import('./src/@core/components/AppLogo.vue')['default']
  const JAlert: typeof import('./src/@core/components/JAlert.vue')['default']
  const JBtn: typeof import('./src/@core/components/JBtn.vue')['default']
  const JCard: typeof import('./src/@core/components/JCard.vue')['default']
  const JCheckbox: typeof import('./src/@core/components/JCheckbox.vue')['default']
  const JDataTable: typeof import('./src/@core/components/JDataTable.vue')['default']
  const JDatePicker: typeof import('./src/@core/components/JDatePicker.vue')['default']
  const JIcon: typeof import('./src/@core/components/JIcon.vue')['default']
  const JInput: typeof import('./src/@core/components/JInput.vue')['default']
  const JModal: typeof import('./src/@core/components/JModal.vue')['default']
  const JPagination: typeof import('./src/@core/components/JPagination.vue')['default']
  const JRadio: typeof import('./src/@core/components/JRadio.vue')['default']
  const JSelect: typeof import('./src/@core/components/JSelect.vue')['default']
  const JSwitch: typeof import('./src/@core/components/JSwitch.vue')['default']
  const JTabs: typeof import('./src/@core/components/JTabs.vue')['default']
  const JTextarea: typeof import('./src/@core/components/JTextarea.vue')['default']
  const JTimePicker: typeof import('./src/@core/components/JTimePicker.vue')['default']
  const JToast: typeof import('./src/@core/components/JToast.vue')['default']
  const JToastContainer: typeof import('./src/@core/components/JToastContainer.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}